<a href="https://colab.research.google.com/github/meghana1209/genai_ml_workshop/blob/main/Workshop_day1_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/homeprices.csv")

In [ ]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
df.columns  #to check the column names

Index(['town', 'area', 'price'], dtype='object')

In [ ]:
df.shape  # to find the rows and columns

(13, 3)

In [ ]:
df.town.value_counts()

town
monroe township    5
west windsor       4
robinsville        4
Name: count, dtype: int64

In [ ]:
df.describe()

area          price
count    13.000000      13.000000
mean   3146.153846  629230.769231
std     453.900475   57621.109914
min    2600.000000  550000.000000
25%    2800.000000  585000.000000
50%    3100.000000  615000.000000
75%    3600.000000  680000.000000
max    4000.000000  725000.000000

In [ ]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
dummies = pd.get_dummies(df.town)  ### Converting categorical to numerical columns with binary values
dummies

monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [ ]:
merged = pd.concat([df, dummies], axis = "columns")

In [ ]:
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [ ]:
merged.drop(["town"], axis = "columns", inplace = True)

KeyError: "['town'] not found in axis"

In [ ]:
merged

area   price  monroe township  robinsville  west windsor
0   2600  550000             True        False         False
1   3000  565000             True        False         False
2   3200  610000             True        False         False
3   3600  680000             True        False         False
4   4000  725000             True        False         False
5   2600  585000            False        False          True
6   2800  615000            False        False          True
7   3300  650000            False        False          True
8   3600  710000            False        False          True
9   2600  575000            False         True         False
10  2900  600000            False         True         False
11  3100  620000            False         True         False
12  3600  695000            False         True         False

When you can derive one variable from other variables, they are known to be multi-colinear. Here if you know values of california and georgia then you can easily infer value of new jersey state, i.e. california=0 and georgia=0. There for these state variables are called to be multi-colinear. In this situation linear regression won't work as expected. Hence you need to drop one column.

In [ ]:
merged.drop(["west windsor"], axis = "columns", inplace = True)

In [ ]:
merged.columns

Index(['area', 'price', 'monroe township', 'robinsville'], dtype='object')

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
X = merged.drop(["price"], axis = "columns") ## Input features data

In [ ]:
y = merged.price   #output variable

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 42)

In [ ]:
X_train.shape

(9, 3)

In [ ]:
X_test.shape

(4, 3)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
X_test

area  monroe township  robinsville
11  3100            False         True
9   2600            False         True
0   2600             True        False
8   3600            False        False

In [ ]:
y_test_pred = model.predict(X_test)

In [ ]:
y_test  #

11    620000
9     575000
0     550000
8     710000
Name: price, dtype: int64

In [ ]:
y_test_pred

array([626917.80821918, 558310.50228312, 528367.57990869, 712716.89497716])

In [ ]:
model.score(X_test,y_test)

0.9460789560707652

In [ ]:
model.score(X_train, y_train)

0.9464717800476193

In [ ]:
X_test

area  monroe township  robinsville
11  3100            False         True
9   2600            False         True
0   2600             True        False
8   3600            False        False

In [ ]:
# ### Predict the house price of a house with the following features
# area = 2500
# town  = robinsville

In [ ]:
# ### Predict the house price of a house with the following features
# area = 3000
# town  = west windsor

In [ ]:
new_data = [2500, 0, 1]

In [ ]:
model.predict([new_data])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([544589.04109591])

In [ ]:
new_data1 = [3000,0,0]

In [ ]:
model.predict([new_data1])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([630388.12785389])